public class WordBank {
    public static String[] commonWords = {
            "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
            "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
            "this", "but", "his", "by", "from", "they", "we", "say", "her",
            "she", "or", "an", "will", "my", "one", "all", "would", "there",
            "their", "what", "so", "up", "out", "if", "about", "who", "get",
            "which", "go", "me", "when", "make", "can", "like", "time", "no",
            "just", "him", "know", "take", "people", "into", "year", "your",
            "good", "some", "could", "them", "see", "other", "than", "then",
            "now", "look", "only", "come", "its", "over", "think", "also",
            "back", "after", "use", "two", "how", "our", "work", "first",
            "well", "way", "even", "new", "want", "because", "any", "day",
            "most", "us", "apple", "banana", "orange", "grape", "computer",
            "science", "data", "program", "code", "file", "network",
            "database", "design", "security", "project", "market", "money",
            "family", "school", "house", "city", "place", "world", "write",
            "read", "listen", "test", "issue", "find", "give", "help",
            "low", "car", "tree", "run", "move", "hold", "try", "ask", "start", "change",
            "high", "little", "long", "great", "small", "important", "public", "social",
            "below", "before", "above", "often", "really", "together", "every", "many",
            "end", "side", "group", "state", "business", "government", "fact", "member",
            "line", "power", "area", "health", "problem", "company", "home", "child",
            "man", "woman", "question", "service", "case", "server", "client", "function",
            "variable", "class", "method", "memory", "internet", "software", "hardware",
            "process", "library", "compile", "debug", "input", "output", "user", "cloud",
            "device", "main", "develop", "easy", "must", "might", "provide", "suggest",
            "receive", "express", "determine", "involve", "require", "support", "achieve", "maintain", "remain",
            "explain", "indicate", "simply", "while", "until", "since", "yet",
            "meanwhile", "although", "therefore", "however", "moreover", "finally",
            "soon", "result", "effort", "quality", "nature",
            "control", "reason", "evidence", "theory", "future",
            "purpose", "material", "research", "strategy", "local", "major", "national", "federal", "personal",
            "simple", "difficult", "clear", "recent", "specific", "physical", "mental",
            "ready", "much", "many", "less", "more", "number", "amount",
            "rate", "level", "size", "total", "measure", "half", "full",
            "friend", "love", "life", "story", "voice", "hope", "belief", "share", "talk", "relate", "feel",
            "happy", "true", "structure", "section", "layer",
            "region", "center", "front", "bottom", "top", "surface", "edge", "core", "framework", "organization",
            "system", "sound", "sight", "smell", "taste", "touch", "warm", "cold", "soft",
            "hard", "dark", "bright", "silent", "loud", "deep", "allow", "appear",
            "belong", "cover", "expect", "mention", "offer", "send",
            "wait", "walk", "suggest", "train", "wish", "law", "policy", "court", "right", "leader", "vote", "election",
            "tax", "budget", "cost", "price", "trade", "industry",
            "firm", "student", "teacher", "class", "study", "knowledge",
            "learn", "lesson", "field", "subject", "discuss", "article",
            "media", "publish", "message", "communication", "carefully",
            "quickly", "slowly", "easily", "suddenly", "eventually",
            "currently", "usually", "rarely", "simply", "personally", "especially", "always", "never", "seldom",
            "daily", "hourly", "weekly",
            "monthly", "early", "late", "moment", "period", "past",
            "different", "similar", "opposite", "versus", "instead", "prevent",
            "accept", "refuse", "greater", "inside", "outside", "order", "course",
            "sense", "field", "report", "role", "turn", "live",
            "meet", "stand", "bring"
    };
}
